// This file was generated by Prisma and assumes you have installed the following:
// pnpm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env('DATABASE_URL'),
    // A shadowDatabaseUrl csak a lokalis 'prisma migrate dev'-hez kellene, a
    // 'db push'/'generate'/futo apphoz nem. Kivettuk, hogy a deploy (Render)
    // ne bukjon el hianyzo SHADOW_DATABASE_URL miatt.
  },
});
